<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Visitacao
* GENERATION DATE:  31.03.2010
* CLASS FILE:       /home/filipo/Projects/elocompany/sql_class_generator/generated_classes/class.Visitacao.php
* FOR MYSQL TABLE:  visitas
* FOR MYSQL DB:     elo_audiovisual1
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("resources/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class Visitacao
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $id;   // KEY ATTR. WITH AUTOINCREMENT

var $ip;   // (normal Attribute)
var $data;   // (normal Attribute)
var $link;   // (normal Attribute)
var $referer;   // (normal Attribute)
var $browser;   // (normal Attribute)
var $os;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function Visitacao()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


/**
 * Retorna o numero de tuplets da ultima query
 * */
public function getNumRows(){
    //$result = $this->database->result;
    return $this->numrows; 
}



function getid()
{
return $this->id;
}

function getip()
{
return $this->ip;
}

function getdata()
{
return $this->data;
}

function getlink()
{
return $this->link;
}

function getreferer()
{
return $this->referer;
}

function getbrowser()
{
return $this->browser;
}

function getos()
{
return $this->os;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function setip($val)
{
$this->ip =  $val;
}

function setdata($val)
{
$this->data =  $val;
}

function setlink($val)
{
$this->link =  $val;
}

function setreferer($val)
{
$this->referer =  $val;
}

function setbrowser($val)
{
$this->browser =  $val;
}

function setos($val)
{
$this->os =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM visitas WHERE id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysql_fetch_object($result);


$this->id = $row->id;

$this->ip = $row->ip;

$this->data = $row->data;

$this->link = $row->link;

$this->referer = $row->referer;

$this->browser = $row->browser;

$this->os = $row->os;

}


function all($where = '1', $ordem = 'id')
{

$sql =  "SELECT * FROM visitas WHERE $where order by $ordem;";
$result =  $this->database->query($sql);
$result = $this->database->result;
while ($row [] = mysql_fetch_object($result)){}

return $row;
}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM visitas WHERE id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->id = ""; // clear key for autoincrement

$sql = "INSERT INTO visitas ( ip,data,link,referer,browser,os ) VALUES ( '$this->ip','$this->data','$this->link','$this->referer','$this->browser','$this->os' )";
$result = $this->database->query($sql);
$this->id = mysql_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE visitas SET  ip = '$this->ip',data = '$this->data',link = '$this->link',referer = '$this->referer',browser = '$this->browser',os = '$this->os' WHERE id = $id ";

$result = $this->database->query($sql);



}


} // class : end
?>
