<?php
require_once 'PHPUnit/Framework.php';

require_once 'includes/classes/FilmeControle.php';

/**
 * Test class for FilmeControle.
 * Generated by PHPUnit on 2010-03-09 at 20:38:50.
 */
class FilmeControleTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var FilmeControle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FilmeControle;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testSelectAllFields().
     */
    public function testSelectAllFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAction().
     */
    public function testAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
