<?php
require_once 'PHPUnit/Framework.php';

require_once 'includes/classes/ListaFilmes.php';

/**
 * Test class for ListaFilmes.
 * Generated by PHPUnit on 2010-03-23 at 20:52:11.
 */
class ListaFilmesTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ListaFilmes
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        echo "------> Iniciando teste ListaFilmes\n";
        $this->object = new ListaFilmes;
        $this->canal = 1;
        $this->busca = "Caquinha";
        $this->webroot = "/cms_blinkx2/";
        $this->records = 8;
        $this->rpp = $this->records;
        $this->pg = 0;        
        $this->start    = $this->pg * $this->rpp ; 
        $this->where    =  '';
        $this->limit    = $this->start.", ".$this->rpp;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        echo "Feito! \n\n";
    }

    /**
     */
    public function testShow()
    {
        // Emulando ambiente web
        $_POST['canal']   = $this->canal;
        $_POST['busca']   = $this->busca;
        $_POST['start']   = $this->start;
        $_POST['rpp']     = $this->rpp;
        $_POST['pg']      = $this->pg;        
 
        echo "testShow\nBuferizando ...\n";
        ob_start();
        // Mostra tela
        $this->object->show();
        $output = ob_get_contents();
        ob_end_clean();
        echo "Fim do Buffer, testando o ambiente\n";
        
        $this->assertContains("<html>", $output, "Ops, nao e' html ...");
        // Os metodos setEnv e setWhere devem montar o ambiente e busca
        $this->assertEquals($this->canal,  $this->object->canal);
        $this->assertEquals($this->busca,  $this->object->busca);
        $this->assertEquals($this->start,  $this->object->start);
        $this->assertContains($this->busca,  $this->object->where);
        $this->assertEquals($this->limit,  $this->object->limit);
        $this->assertEquals($this->webroot,$this->object->webroot);
        $this->assertEquals($this->records,$this->object->records);
        $this->assertEquals($this->rpp,    $this->object->rpp);
        $this->assertEquals($this->pg,     $this->object->pg);  
        echo "Passou em todos os testes\n--------------------------\n";      
    }
}
?>
