<?php
require_once 'PHPUnit/Framework.php';
require_once 'includes/classes/PlanilhaStore.php';
require_once 'includes/classes/Filme.php';
require_once 'includes/config.inc.php';

function getOffset(){
    global $offset;
    return $offset;
}

function getTitulos(){
    global $campos_import;
    return $campos_import;
}

function getCsv(){
    return "data/uploads/anima.csv";
}


/**
 * Test class for PlanilhaStore.
 * Generated by PHPUnit on 2010-03-09 at 20:43:37.
 */
class PlanilhaStoreTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var PlanilhaStore
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PlanilhaStore(getCsv(),getTitulos());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testVerifyCsv().
     */
    public function testVerifyCsv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testError().
     */
    public function testError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetCsv().
     */
    public function testSetCsv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetCsv().
     */
    public function testGetCsv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testLoadCsv().
     */
    public function testLoadCsv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSaveBd().
     */
    public function testSaveBd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetMappedData().
     */
    public function testGetMappedData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetData().
     */
    public function testGetData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetTitles().
     */
    public function testSetTitles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMapTitles().
     */
    public function testMapTitles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetTitles().
     */
    public function testGetTitles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
